### ISSUE TITLE
yarn start fails - https://github.com/hotwired/stimulus-starter.git

### ISSUE THREAD

**Issue by cmoulliard** [stimulusjs/stimulus-starter#19]
## Issue

yarn start fails - https://github.com/hotwired/stimulus-starter.git

```
git clone https://github.com/hotwired/stimulus-starter.git
Cloning into 'stimulus-starter'...
remote: Enumerating objects: 165, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 165 (delta 39), reused 34 (delta 34), pack-reused 117
Receiving objects: 100% (165/165), 361.58 KiB | 2.94 MiB/s, done.
Resolving deltas: 100% (89/89), done.

cd stimulus-starter
yarn install

yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 18.61s.
 ~/temp/stimulus-starter   main  yarn start
yarn run v1.22.19
$ node server.js
Listening on port 9000
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/cmoullia/temp/stimulus-starter/node_modules/babel-loader/lib/index.js:59:71
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

npx browserslist@latest --update-db
Need to install the following packages:
  browserslist@4.21.4
Ok to proceed? (y) y
Current version: 1.0.30001104
New version: 1.0.30001425
Updating caniuse-lite…
caniuse-lite has been successfully updated%

yarn start
yarn run v1.22.19
$ node server.js
Listening on port 9000
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cmoullia/temp/stimulus-starter/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/cmoullia/temp/stimulus-starter/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/cmoullia/temp/stimulus-starter/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by corasaurus-hex** [comment]
It works with node 16.16, seems to be a node version issue

**Comment by corasaurus-hex** [comment]
and 16.18. didn't test 17 at all, though
